# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cschema.proto\x12\x06schema\"*\n\x04User\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x11\n\tuser_name\x18\x02 \x01(\t\"\x0e\n\x0c\x45mptyMessage\"\x18\n\x06status\x12\x0e\n\x06status\x18\x01 \x01(\x08\"$\n\x05Users\x12\x1b\n\x05users\x18\x01 \x03(\x0b\x32\x0c.schema.User2\x96\x01\n\x08\x44\x61tabase\x12)\n\x07PutUser\x12\x0c.schema.User\x1a\x0e.schema.status\"\x00\x12,\n\nDeleteUser\x12\x0c.schema.User\x1a\x0e.schema.status\"\x00\x12\x31\n\x08GetUsers\x12\x14.schema.EmptyMessage\x1a\r.schema.Users\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schema_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USER._serialized_start=24
  _USER._serialized_end=66
  _EMPTYMESSAGE._serialized_start=68
  _EMPTYMESSAGE._serialized_end=82
  _STATUS._serialized_start=84
  _STATUS._serialized_end=108
  _USERS._serialized_start=110
  _USERS._serialized_end=146
  _DATABASE._serialized_start=149
  _DATABASE._serialized_end=299
# @@protoc_insertion_point(module_scope)
