# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\x12\ncalculator\"\x07\n\x05\x45mpty\"\x1f\n\x07Numbers\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\x18\n\x06Result\x12\x0e\n\x06result\x18\x01 \x01(\x02\x32\x99\x02\n\nCalculator\x12\x30\n\x03\x41\x64\x64\x12\x13.calculator.Numbers\x1a\x12.calculator.Result\"\x00\x12\x35\n\x08Subtract\x12\x13.calculator.Numbers\x1a\x12.calculator.Result\"\x00\x12\x35\n\x08Multiply\x12\x13.calculator.Numbers\x1a\x12.calculator.Result\"\x00\x12\x33\n\x06\x44ivide\x12\x13.calculator.Numbers\x1a\x12.calculator.Result\"\x00\x12\x36\n\x0bPrintResult\x12\x12.calculator.Result\x1a\x11.calculator.Empty\"\x00\x42\r\xaa\x02\nCalculatorb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\nCalculator'
  _EMPTY._serialized_start=32
  _EMPTY._serialized_end=39
  _NUMBERS._serialized_start=41
  _NUMBERS._serialized_end=72
  _RESULT._serialized_start=74
  _RESULT._serialized_end=98
  _CALCULATOR._serialized_start=101
  _CALCULATOR._serialized_end=382
# @@protoc_insertion_point(module_scope)
